language: python
python:
    - "2.7"

before_install:
    - sudo apt-get update
    - sudo apt-get install gdal-bin libgdal1h python-gdal
    - sudo apt-get install python-qt4

install:
    - which pip
    - pip install --allow-external dbfpy
    - which python
    - python setup.py install

script: nosetests test/validation_test.py
