language: python
python:
    - "2.7"

before_install:
    - sudo apt-get update
    - sudo apt-get install gdal-bin libgdal1 python-gdal
    - sudo apt-get install python-qt4

install:
    - pip install dbfpy
    - python setup.py install

script: nosetests palisades
