language: python
python:
    - "2.7"

virtualenv:
    system_site_packages: true

before_install:
    - sudo apt-get update
    - sudo apt-get install python-qt4
    - sudo apt-get install gdal-bin libgdal1h python-gdal

install:
    - pip install --allow-all-external --allow-unverified dbfpy dbfpy
    - python setup.py install

script: nosetests test/validation_test.py
